### PR TITLE
Change boot logic

### PR DESCRIPTION
**Pull request by scaronni**
A simpler way to deal with https://github.com/openSUSE/nvidia-driver-G06/issues/62.

Always add modules to the `initrd`. Benefits:

- The `blacklist nouveau` line is added to the initrd, even in the first installation.
- There is no need to add the soft dependency rule to `modprobe`, as also `nvidia-uvm` is added to the `initrd`.
- There is no need to for the `dracut` configuration file anymore.
- There is no need to invent a way to blacklist `nouveau` in the `initrd` without touching it.
- The boot process is at the native resolution of the display as the modules are in the `initrd`.

Extra: remove the echo stuff for Nouveau, I think it's really not needed and it's printed only for closed modules.

### CODE REVIEW

**Comment by scaronni** [comment]
This doesn't work 100% correctly as there is no `depmod` being run during uninstall, so the `initird` in the uninstall case does not remove the NVIDIA modules.

**Comment by scaronni** [comment]
Also the file `/usr/lib/modprobe.d/50-nvidia.conf` does not get included (thus not blacklisting `nouveau`) on the **first** initrd rebuild. I guess this is because the transaction runs after the kernel module package gets installed, and not at the end of the transaction.

Probably this is more complicated than adding the kernel boot parameter.

**Comment by scaronni** [comment]
I'll rethink it with triggers, putting back in draft.

**Comment by scaronni** [comment]
> Hmm. But dracut is running in %post/%postun, so modules should be added /removed from initrd. 

Not if `depmod` has not run, as it looks for the NVIDIA modules in `depmod` and just fails to run. So it would also need the code snippet to also detect the kernel version as in `kmp-post.sh`, which is another bunch of code.

> `/usr/lib/modprobe.d/50-nvidia.conf` is part of `nvidia-common-G06`, so if this is being installed after installing the KMP it won't be included in initrd. Unfortunately there is no `Recommends(pre): nvidia-common-G06`, just `Requires(pre) ...`. 

Yeah, if it was instead a `Requires:` it would get installed earlier and the file would be there, but since you're signing open modules in the separate package without the firmware you can't use `Requires`.

Therefore my suggestion to use
> 
> ```
> %post nvidia-common-G06
> pbl --add-option modprobe.blacklist=nouveau --config
> ```
> 
> ```
> %postun -n nvidia-common-G06
> pbl --del-option modprobe.blacklist=nouveau --config
> ```
> 
> for blacklist `nouveau` instead.

Yeah, probably is the least painful.

**Comment by scaronni** [comment]
> Therefore my suggestion to use
> 
> ```
> %post nvidia-common-G06
> pbl --add-option modprobe.blacklist=nouveau --config
> ```
> 
> ```
> %postun -n nvidia-common-G06
> pbl --del-option modprobe.blacklist=nouveau --config
> ```
> 
> for blacklist `nouveau` instead.

I think this should be `rd.driver.blacklist=nouveau` instead of `modprobe.blacklist=nouveau`.

**Comment by scaronni** [comment]
Another option is to add `nouveau` to `%{_prefix}/lib/dracut/dracut.conf.d/60-nvidia.conf` and rebuild anyway the initrd so it gets excluded, and then there's no need for a command line paraemter. Half in between the two options, basically.

I'll make some more tests on which one is the most feasible one.

**Comment by sndirsch** [comment]
Ok. Omitting `nouveau` from initrd may also help, since it will likely refuse from loading if `nvidia` is already loaded. But blacklisting looks much cleaner to me. You're right. Needs to be `rd.driver.blacklist=nouveau` instead in case this driver lands in `initrd`. Ouch.

**Pull request closed without merging**
