### PR TITLE
Drop initrd manipulation

### PR DESCRIPTION
**Pull request by scaronni**
Do not add Nvidia kernel modules also on non-Optimus / Nvidia only systems.

There's no need for preloading the modules in the `initrd`, the only thing you're missing from not doing this is the console framebuffer being set at the proper resolution during boot. In case of an Nvidia only system, `efifb`, `simpledrm` or the other drivers will take care of displaying prompts, console, plymouth password prompts, etc.

This is being done already in the `nvidia-open-driver-G06` case, where the modules are never added to the `initrd`: https://github.com/openSUSE/nvidia-open-driver-G06/blob/main/nvidia-open-driver-G06.spec#L223-L225

### CODE REVIEW

**Comment by sndirsch** [comment]
Unfortunately I can't remember why I changed that:

commit 31fd53799659dcb654db36bb183c938e592c9e3b
Author: Stefan Dirsch <sndirsch@suse.de>
Date:   Tue Oct 31 13:04:48 2023 +0100

    changes in kmp-post.sh/kmp-trigger.sh and kmp-filelist
    
    - kmp-post.sh/kmp-trigger.sh
      * load modules already in initrd on non-Optimus, i.e. nVidia-only
        systems

**Comment by sndirsch** [comment]
Years ago I did the opposite:

+Tue Jul 21 09:08:17 UTC 2020 - Stefan Dirsch <sndirsch@suse.com>
+
+- added /etc/dracut.conf.d/60-nvidia-default.conf in order to
+  omit nvidia modules in initrd, which apparently were added
+  automatically on many systems - apart from nvidia-uvm module! -
+  which then made GPU computing/CUDA impossible on all theses
+  systems (boo#1173733)

**Comment by scaronni** [comment]
I think it's wrong. We're omitting everything in dracut also for the closed source modules [since a very long time](https://github.com/negativo17/nvidia-kmod-common/blob/master/99-nvidia.conf) and we're using a [softdep](https://github.com/negativo17/nvidia-kmod-common/blob/master/nvidia.conf#L1-L17) for `nvidia-uvm` after the system is booted.

This is for all distributions (also the power management lines above, but that's a separate topic).

**Comment by scaronni** [comment]
The only thing that the module in the initrd is the native KMS resolution when `nvidia-drm` loads, nothing else.

And anyway you're doing it for the open modules, which are now the default.

**Comment by scaronni** [comment]
Mosf of the distributions rely on either `efifb`, `vesa` or `simpledrm`, all of which `nvidia-drm` takes over. Isn't that the case with the various Suse variants?

**Comment by sndirsch** [comment]
Yes, that's how things should behave. Anyway, consistency is an argument. Let's have the same behaviour here as with the opengpu kernel modules. But then we should changes this also the same way in `kmp-trigger.sh`.

**Comment by sndirsch** [comment]
Let's take it as is. I'll make another commit for `kmp-trigger.sh` later.

**Comment by sndirsch** [comment]
> Let's take it as is. I'll make another commit for `kmp-trigger.sh` later.

Done. https://github.com/openSUSE/nvidia-driver-G06/commit/eb04e24390175e52eab645e2b2448ca28e8d2d14

**Pull request merged**
