### PR TITLE
Update to 565.57.01

### PR DESCRIPTION
**Pull request by scaronni**
Not much... This of course needs updating version etc. to 565.57.01. Shall I do it?

### CODE REVIEW

**Comment by sndirsch** [comment]
> Not much... This of course needs updating version etc. to 565.57.01. Shall I do it?

You mean raise the version number in the specfiles? Sure. Go ahead! .run files have been released.

**Comment by scaronni** [comment]
ok!

**Comment by scaronni** [comment]
@akontsevich i don't work for Suse.

**Comment by akontsevich** [comment]
> @akontsevich i don't work for Suse.

Is this openSUSE repo? Does somebody know here?

**Comment by sndirsch** [comment]
> @sndirsch @scaronni guys any idea when 560 will be available in https://download.nvidia.com/opensuse/tumbleweed? Thanks!

In these repos you will only find packages for production branch drivers. 560/656 is a feature branch driver. I'm not allowed to speak about the driver release schedule of nvidia. Please be patient.

**Comment by scaronni** [comment]
Changed version and changelog as well.

**Comment by sndirsch** [comment]
Looks good. Thanks!

**Pull request merged**
