### PR TITLE
Automate PCI ID files generation

### PR DESCRIPTION
**Pull request by scaronni**
Another attempt at automating, starting from the closed driver.

This changes the python script to get all the information from the `supported-gpus.json` file so it can be called during the SPEC build:

```
$ ./json-to-pci-id-list.py 565.57.01 NVIDIA-Linux-x86_64-565.57.01/supported-gpus/supported-gpus.json 
Generated pci_ids-565.57.01.full (non-legacy)
Generated pci_ids-565.57.01.closed (non-legacy, supported by closed modules only)
Generated pci_ids-565.57.01.open (non-legacy, supported by open modules only)
```

Logic is as follows:
- full means anything supported by the current driver, so excludes anything with legacy branches.
- closed means anything supported by the current driver, only by the closed module
- open means anything supported by the current driver only by the open module

Besides this, it drops support for "legacy" branches in `my-find-supplements`, as 470 was the last one and is now end of life.

### CODE REVIEW

**Comment by scaronni** [comment]
@sndirsch let me know what you think.

**Comment by sndirsch** [comment]
> @sndirsch let me know what you think. I think there is some mistake in the previous logic for the PCI IDs unless I miss something on what is the selection required to generate them.

Ok. I removed the duplicates of same Device ID, since in RPM Supplements lines there is only the PCI ID left and used for auto-selection of the package.
And I used to remove the Tesla GPUs, since these were/are coming without graphical output. Hope this assumption was/is still correct. But with CUDA this point of view might no longer be valid and I should add them again.

**Comment by sndirsch** [comment]
Thanks for the new script. 
> Generated pci_ids-565.57.01.closed (non-legacy, supported by closed modules only)
That's the one I'm interested in. I used the existing script to generated non-legacy and  open-only. Then "removed" the ids from open-only result from non-legacy.

The meaning of the `pci_ids-%version.new` file is: I t contains the IDs, which are not yet supported by the legacy driver 470.xx, so customers don't get autoselected G05 and G06 driver at the same time on sle15 < SP4

**Comment by sndirsch** [comment]
Also I did a quick build test and no Supplements are created. I think

```
%{SOURCE26} %{version} supported-gpus/supported-gpus.json
```

needs to be done in build section instead. 

Whatever, I believe with https://github.com/openSUSE/nvidia-driver-G06/pull/48  we're done. I doubt that the support for Pascal/Maxwell/Volta GPUs will ever change again. So we can live with a static configuration here I think. For the open diver I openen a pull request for a dynamic configuration.

**Comment by scaronni** [comment]
> Ok. I removed the duplicates of same Device ID, since in RPM Supplements lines there is only the PCI ID left and used for auto-selection of the package. And I used to remove the Tesla GPUs, since these were/are coming without graphical output. Hope this assumption was/is still correct. But with CUDA this point of view might no longer be valid and I should add them again.

I would personally leave all them in. We leave the entire set it for the builds.

> The meaning of the pci_ids-%version.new file is: It contains the IDs, which are not yet supported by the legacy driver 470.xx, so customers don't get autoselected G05 and G06 driver at the same time on sle15 < SP4

We don't support 470 anymore and we don't really have one driver or the other, either a driver supports a card or not and then you can pick one of the supported branches. So there is no "difference" with one driver from the previous, it's just a new iteration of the same basically. Are you sure you still want to suggest 470 for some GPUs? I don't think you should.

> Also I did a quick build test and no Supplements are created. I think
> %{SOURCE26} %{version} supported-gpus/supported-gpus.json
> needs to be done in build section instead.

Correct, sorry, it's only a draft to check if the whole logic was fine for you.

> Whatever, I believe with #48 we're done. I doubt that the support for Pascal/Maxwell/Volta GPUs will ever change again. So we can live with a static configuration here I think. For the open diver I openen a pull request for a dynamic configuration.

Ok, so no automation. I see, if you're not dropping the PCI IDs as a delta of 470 there is no need for this. Considering we have a different requirement I'll see to import a variant of this merge request for us.

**Comment by sndirsch** [comment]
Ok. Understood. I'm considering removing PCI ID supplements from no longer supported G0x driver series.  Believe me, you don't want to know how many users are still running systems with Kepler and older GPUs. But no longer suggesting to use them makes perfectly sense.

**Comment by sndirsch** [comment]
https://github.com/openSUSE/nvidia-driver-G06/pull/48 accepted now. Therefore closing this now.

**Pull request closed without merging**
