### PR TITLE
Automate generation of PCI IDs

### PR DESCRIPTION
**Pull request by scaronni**
Automate generation of PCI IDs at build time, not prior to building. If this works for you, I'll do a similar merge request for `nvidia-open-driver-G06`.

Extra: drop Xwrapper, it's declared but not used.

### CODE REVIEW

**Comment by sndirsch** [comment]
I really like the idea of generating this information automatically during build time. But my plan is autoselect this proprietary kernel driver only for GPUs < Turing. So let's try to do such automatic stuff for the open driver and maintain the list for GPUs < Turing manually. Probably it will never change anyway then.

Removing Xwrapper is a non-brainer. Thanks for doing cleanups.

**Comment by sndirsch** [comment]
Unfortunately for `nvidia-open-driver-G06` we're lacking `.run` file. There we have the information in `README.md` of the sources, but I don't know how reliable that is.  OTOH `json-to-pci-id-list.py` has also this `--kernelopen` option for the open driver.

**Comment by scaronni** [comment]
Just out of curiosity, why this repository has the userland part + closed module together and the open module is in a separate repository?

**Comment by scaronni** [comment]
I'll think more about it, I guess for now you can just drop the Xwrapper file.

**Comment by sndirsch** [comment]
> Just out of curiosity, why this repository has the userland part + closed module together and the open module is in a separate repository?

It's related to the secureboot signing process. Also it's our policy to provide official KMP packages via our maintenance process. The closed module package is not really a KMP. The driver is built during installation as you surely know.

**Comment by sndirsch** [comment]
> I'll think more about it, I guess for now you can just drop the Xwrapper file.

Thanks. I'll take care of removing Xwrapper file.

**Pull request closed without merging**
