### PR TITLE
Use external packages for nvidia-persistenced/nvidia-settings/nvidia-xconfig/nvidia-modprobe (gh issue#16)

### PR DESCRIPTION
**Pull request by sndirsch**

### CODE REVIEW

**Comment by sndirsch** [comment]
@scaronni-nvidia I guess this one is ok now. More tomorrow ...

**Comment by sndirsch** [comment]
@scaronni-nvidia I'm done with this issue #16 . Reorganization (issue #15 ) will be another and separate step.

**Comment by sndirsch** [comment]
Assuming this is ok

**Comment by scaronni** [comment]
Hi Stefan, where is the package for `nvidia-modprobe`? I found the other 3:

- https://build.opensuse.org/package/show/openSUSE:Factory/nvidia-persistenced
- https://build.opensuse.org/package/show/openSUSE:Factory/nvidia-settings
- https://build.opensuse.org/package/show/openSUSE:Factory/nvidia-xconfig

**Comment by scaronni** [comment]
Ah, is it this one? https://build.opensuse.org/package/show/X11:XOrg/nvidia-modprobe

**Comment by sndirsch** [comment]
> Ah, is it this one? https://build.opensuse.org/package/show/X11:XOrg/nvidia-modprobe

Yes. That's it. We still have a security audit running for it. So it wasn't checked in into openSUSE:Factory yet.

**Comment by sndirsch** [comment]
But you can assume these packages will be available. They will be in the repository together with the other packages built from the .run file. No matter if they are on the product or not.

**Comment by scaronni** [comment]
It seems the same for the egl libraries, will they be **only** under `openSUSE:Factory` and not under `X11:XOrg`? Or both? 

- https://build.opensuse.org/package/show/X11:XOrg/libnvidia-egl-x11
- https://build.opensuse.org/package/show/openSUSE:Factory/libnvidia-egl-x11
- https://build.opensuse.org/package/show/X11:XOrg/libnvidia-egl-gbm
- https://build.opensuse.org/package/show/openSUSE:Factory/libnvidia-egl-gbm
- https://build.opensuse.org/package/show/X11:XOrg/libnvidia-egl-wayland
- https://build.opensuse.org/package/show/openSUSE:Factory/libnvidia-egl-wayland

I'm asking because I'm keeping an internal copy, it might be that we have an internal patch or yet unreleased commits that go along with another driver; so I would like to know onto which one to keep an eye on. Is it `openSUSE:Factory` or `X11:XOrg`?

**Comment by sndirsch** [comment]
> It seems the same for the egl libraries, will they be **only** under `openSUSE:Factory` and not under `X11:XOrg`? Or both?
> 
> * https://build.opensuse.org/package/show/X11:XOrg/libnvidia-egl-x11
> * https://build.opensuse.org/package/show/openSUSE:Factory/libnvidia-egl-x11
> * https://build.opensuse.org/package/show/X11:XOrg/libnvidia-egl-gbm
> * https://build.opensuse.org/package/show/openSUSE:Factory/libnvidia-egl-gbm
> * https://build.opensuse.org/package/show/X11:XOrg/libnvidia-egl-wayland
> * https://build.opensuse.org/package/show/openSUSE:Factory/libnvidia-egl-wayland
> 
> I'm asking because I'm keeping an internal copy, it might be that we have an internal patch or yet unreleased commits that go along with another driver; so I would like to know onto which one to keep an eye on. Is it `openSUSE:Factory` or `X11:XOrg`?

X11:XOrg is the development project for openSUSE:Factory (=Tumbleweed). So these will be all on Tumbleweed. But I can and will build these also for sle15/Leap15

libnvidia-egl-gbm: sle15-sp5/Leap15.5 and higher
libnvidia-egl-wayland: sle15-sp7/Leap 15.7 and higher
libnvidia-egl-x11: sle15-sp6/Leap 15.7 and higher

This is also specified that way in the specfile already. These will get pushed together with all the other packages into the nvidia repository. So it doesn't matter that they aren't on the sle/Leap product itself.

**Pull request merged**
