### PR TITLE
560 rebase (depends on #9)

### PR DESCRIPTION
**Pull request by scaronni**
**This merge request is on top of https://github.com/openSUSE/nvidia-driver-G06/pull/9, once that is merged, this can be rebased and the commits contained in the above merge request will disappear.**

Adds all the extra bits and pieces for driver 560. The Vulkan Safety Critical components ICD installation follows the same logic that is used in the previous merge request for standardizing the ICD installation.

Driver 560 requires EGL libraries at the following minimum versions to work. Please note that on `x86_64` the libraries are needed in **both** 64 bit and 32 bit form, otherwise launching 32 bit applications in a Wayland/EGL context will fail.

- [egl-gbm](https://github.com/NVIDIA/egl-gbm) 
  - Minimum version is 1.1.2.
- [egl-wayland](https://github.com/NVIDIA/egl-wayland)
  - Minimum version is 1.1.13.1
  - Version 1.1.13.1 is just 1.1.13 with driver 560 compatibily, there is no Wayland Explicit Sync
  - Version 1.1.16+ is required for proper Wayland Explicit Sync support for applications running `Xwayland` (ex. Steam games, etc.).
- [egl-x11](https://github.com/NVIDIA/egl-x11)
  - Minimum version is 0.1
  - Building this requires [eglexternaplatform](https://github.com/NVIDIA/eglexternalplatform) at minimum version 1.2.

Not knowing any better, the conditionals for the EGL libraries have been left as `0%{?suse_version} < 1550` and similar. Ideally these will be packaged in separate components:
```
eglexternalplatform-devel-<version>-<release>.noarch.rpm
```
```
libnvidia-egl-wayland1-<version>-<release>.aarch64.rpm
libnvidia-egl-wayland1-<version>-<release>.x86_64.rpm
libnvidia-egl-wayland1-32bit-<version>-<release>.x86_64.rpm
libnvidia-egl-wayland-devel-<version>-<release>.aarch64.rpm
libnvidia-egl-wayland-devel-<version>-<release>.x86_64.rpm
```
```
libnvidia-egl-gbm1-<version>-<release>.aarch64.rpm
libnvidia-egl-gbm1-<version>-<release>.x86_64.rpm
libnvidia-egl-gbm1-32bit-<version>-<release>.x86_64.rpm
```
```
libnvidia-egl-x111-<version>-<release>.aarch64.rpm
libnvidia-egl-x111-<version>-<release>.x86_64.rpm
libnvidia-egl-x111-32bit-<version>-<release>.x86_64.rpm
```

As Nvidia we are trying to package anything that can be built from open source components to be built from sources (this will include `nvidia-settings`, `nvidia-modprobe`, `nvidia-xconfig` and `nvidia-persistenced`).

### CODE REVIEW

**Comment by scaronni** [comment]
@sndirsch could you at least merge in a non-used branch? So at least I know where to base merge requests on.

Thanks.

**Comment by sndirsch** [comment]
> @sndirsch could you at least merge in a non-used branch? So at least I know where to base merge requests on.

I was considering to make a branch for >= 550.120 releases so you can base merge on main branch. I plan to switch to a new release with the next production branch driver, for which I then can add the next branch. So this way `main` remains clean for your changes. Does this make sense?

**Comment by scaronni** [comment]
Yes please, so then I can send you the other changes. It's a bit complicated otherwise.

**Comment by sndirsch** [comment]
> Yes please, so then I can send you the other changes. It's a bit complicated otherwise.

Great. Just created `550.120-and-greater-branch` on latest commit for specific for 550.120. So further changes by me specific to 550 releases will go there. With that I think I can merge this PR #10 .

**Comment by sndirsch** [comment]
Thanks for the PR. Looks good!

**Pull request merged**
