### PR TITLE
Use external package for nvidia-persistenced on Tumbleweed (gh issue#16)

### PR DESCRIPTION
**Pull request by sndirsch**

### CODE REVIEW

**Comment by sndirsch** [comment]
@scaronni-nvidia Next trivial PR. I guess this is ok as well?

**Comment by scaronni** [comment]
On this one I'm not convinced sorry. Why can't you also build persistenced on any version besides tumbleweed? It builds fine even on 15.0.

These extra packages should be built as part of the driver build (separate spec file, but together like the other two) or as a complete separate package. If you can push a driver update (let's say 550.120), you can also push persistenced, right?

**Comment by sndirsch** [comment]
> On this one I'm not convinced sorry. Why can't you also build persistenced on any version besides tumbleweed? It builds fine even on 15.0.
> 
> These extra packages should be built as part of the driver build (separate spec file, but together like the other two) or as a complete separate package. If you can push a driver update (let's say 550.120), you can also push persistenced, right?

Oh. It's just the same as with that: https://github.com/openSUSE/nvidia-driver-G06/pull/18#issuecomment-2374037504

**Comment by scaronni** [comment]
I don't get it.

When there is a driver update, you're pushing out the packages that are built from `nvidia-driver-G06.spec`, `nvidia-video-G06.spec`, `nvidia-open-driver-G06.spec` and `kernel-firmware-nvidia-gspx-G06.spec` all together, so what's different with those 4 pacakges?

Why can't you add the packages that get built from `nvidia-settings.spec`, `nvidia-xconfig.spec`. `nvidia-persistenced.spec` and nvidia-modprobe.spec` for the driver release?

The egl packages are different, as they depend on other stuff (like GBM support in Mesa, etc.) and can be used by other packages as well (in fact you already have `egl-wayland`), but these packages are part of the driver.

**Comment by scaronni** [comment]
Ideally you should bundle only when you can not build. So EGL libraries might not build in older Suse releases etc. But these have minimal dependencies.

**Comment by scaronni** [comment]
My idea would be to reduce the complexity of the SPEC file, not increasing it with dozens of if conditions. The suse SPEC file & supporting files is the most complicated we have in all the distributions we support, the other ones are much simpler. Ex. for the `nvidia-modprobe` udev rule example in the other thread:

- Drops files from the main driver SPEC files
- Drops tons of udev rules
- Adds one udev rules that catches all

If we increase the conditions etc. then probably for you it's not worth splitting at all those components.

**Comment by scaronni** [comment]
Up to you!

**Comment by sndirsch** [comment]
I will rework the PR. :-)

**Comment by scaronni** [comment]
If you want, I can do the PR which just requires those packages in place of the other binaries. Is that ok?

Maybe I can do combined with reorganizing the components between packages.

**Comment by sndirsch** [comment]
> If you want, I can do the PR which just requires those packages in place of the other binaries. Is that ok?

I think this is straight forward. I will work on this.

> Maybe I can do combined with reorganizing the components between packages.

I would prefer to do this in a second step after discussing in more detail issue#15. Ok?

**Pull request closed without merging**
