### PR TITLE
Batch 2, No.1 - Simplify installation

### PR DESCRIPTION
**Pull request by scaronni**
Thanks for taking care of the previous changes. Here is some new stuff, now that everything gets less cluttered we can simplify the installation a bit:

### Remove all the not neeeded components in one place, before installing everything

- Removes all the `rm` commands scattered across the SPEC file, everything is in one place. Instead of adding & removing later, just don't add.
- What is left at the end of the `%prep` section it's what needs to be installed (symlinks included), no more no less. With a `rpmbuild -bp` you can just check what needs to be packaged, new files, etc.
- Uses way less `ldconfig` commands in just the `%prep` section.
- Drops the creation of the `/usr/X11R6` directory, `ldconf` configuration file, all subdirectories and `libGL.so/libGL.so.1` symlinks, before throwing everything away (?).

### Fixes the EGL GBM ICD installation

The `15_nvidia_gbm.json` file should be installed only if `egl-gbm` is not installed from external sources, like the rest of the `egl-*` packages.

### CODE REVIEW

**Comment by scaronni** [comment]
Each topic is divided by commit, if you want to have a look.

**Comment by sndirsch** [comment]
Thanks a lot. I got the idea an I think this is a good change. Probably I need to rework the egl json files changes a bit (issue #26), but I will do this once you're done with your pull requests.

**Comment by scaronni** [comment]
This merge requests assumes the json files are shipped as part of the respective packages, as we're doing here.

**Comment by sndirsch** [comment]
I see. You even already integrated my changes from issue #26. I had a build test against Tumbleweed and needed a small patch to fix the build issues. When you build against Tumbleweed `%sle_version` is not set. That's confusing I know.
[fix4pr27.patch.txt](https://github.com/user-attachments/files/17281206/fix4pr27.patch.txt)

**Comment by scaronni** [comment]
If it's fine for you, just apply your fix, and for the next one I'm preparing right now I'll just rebase on the main branch.

**Comment by sndirsch** [comment]
> If it's fine for you, just apply your fix, and for the next one I'm preparing right now I'll just rebase on the main branch.

done. I've directly made a commit f10d35e10da457b96c96b30fec202b8bbf2a6bc4 instead of extra opening a pull request. Hope this is ok for you.

**Comment by scaronni** [comment]
Your repository your rules! :)

**Pull request merged**
