### PR TITLE
update pci ids to version 560.35.03, but remove IDs supported by open…

### PR DESCRIPTION
**Pull request by sndirsch**
… driver

So basically what is remaining here is Maxwell and Pascal GPUs

### CODE REVIEW

**Comment by sndirsch** [comment]
@scaronni-nvidia JFYI ...

**Comment by scaronni** [comment]
Why not 565.57.01 like for the open driver?

**Comment by sndirsch** [comment]
> Why not 565.57.01 like for the open driver?

1. We haven't updated these package sources yet to 565.57.01
2. The only difference between 560.35.03 and 565.57.01 is the support for additional Hopper/Grace Hopper 200 GPUs, that's for sure no Maxwell/Pascal GPU, so it just doesn't matter.

**Comment by sndirsch** [comment]
> > Why not 565.57.01 like for the open driver?
> 
> 1. We haven't updated these package sources yet to 565.57.01

Wrong. Seems I forgot about you  update to 565.57.01. I apologize. Will do another update to rename the pci id files.

**Pull request merged**
