### PR TITLE
Avoid globbing (depends on #4)

### PR DESCRIPTION
**Pull request by scaronni**
**This merge request is on top of https://github.com/openSUSE/nvidia-driver-G06/pull/4, once that is merged, this can be rebased and the commit contained in the above merge request will disappear.**

Avoid globbing everywhere, it makes it very hard to edit and check which file is where. Instead of globbing everything and adding excludes all over the place, do the opposite, explicitly declare where files are.

On top of that, do not ship the `nvidia-persistenced-init.tar.bz2` tarball in git and associated scripts, what `nvidia-persistenced` needs it's just a simple `systemd` unit.

### CODE REVIEW

**Comment by scaronni** [comment]
Rebased.

**Comment by e4t** [comment]
The diff in 'Avoid globbing' now contains rebase artefacts  - like `<<<<<<< HEAD`

**Comment by scaronni** [comment]
Fixed, sorry, let's check the opencl one before rebasing again.

**Comment by scaronni** [comment]
Rebased on latest `main`.

**Comment by scaronni** [comment]
Nope, sorry, 1 second. On our side it was done after many commits bringing up to 560. I missed a few pieces.

**Pull request merged**
